using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Abode.Tables
{
    public class Messages
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)] // Indicates that the value is generated by the database
        public int key { get; set; }
        public int? propertyID { get; set; }
        public string? landlordUsername { get; set; }
        public string? tenantUsername { get; set; }
        public string? messages { get; set; }
        public DateTime? dateTime { get; set; }
        public string? studentUsername { get; set; }



    }
}
